language: go

go:
  - 1.19
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go test
  - go test -run FuzzParsePlayerInfo -fuzz FuzzParsePlayerInfo -fuzztime 1m
